# Generated by Django 4.0.4 on 2022-04-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('mail', models.EmailField(max_length=254, verbose_name='Ingrese Correo del Cliente')),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
