# Generated by Django 4.0.4 on 2022-04-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTelovendo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=60, verbose_name='Ingrese nombre del proveedor')),
                ('categoria', models.CharField(max_length=60, verbose_name='Ingrese categoria del proveedor')),
                ('direccion', models.CharField(max_length=60, verbose_name='Ingrese la direccion del proveedor')),
                ('telefono_proveedor', models.IntegerField(verbose_name='Ingrese Telefono del proveedor')),
                ('email_proveedor', models.EmailField(max_length=254, verbose_name='Ingrese Correo del Proveedor')),
            ],
        ),
    ]
