# Generated by Django 4.0.4 on 2022-04-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTelovendo', '0002_provedore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venderor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('mail', models.EmailField(max_length=254, verbose_name='Ingrese Correo del Cliente')),
                ('telefono', models.IntegerField()),
                ('fecha_contratacion', models.DateField()),
            ],
        ),
    ]
