# Generated by Django 4.0.4 on 2022-04-29 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTelovendo', '0003_venderor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venderor',
            new_name='Vendedor',
        ),
    ]
