# Generated by Django 4.0.4 on 2022-05-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTelovendo', '0004_rename_venderor_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedore',
            name='categoria',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='provedore',
            name='direccion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='provedore',
            name='nombre_proveedor',
            field=models.CharField(max_length=60),
        ),
    ]
