# Generated by Django 4.0.4 on 2022-05-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTelovendo', '0005_alter_provedore_categoria_alter_provedore_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
