# Generated by Django 4.0.4 on 2022-05-17 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTelovendo', '0006_comentarios_alter_vendedor_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='provedore',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppTelovendo.categoria'),
        ),
    ]
