# Generated by Django 4.0.4 on 2022-05-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTelovendo', '0009_alter_categoria_nombre_alter_provedore_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='subcategoria',
            field=models.ManyToManyField(null=True, to='AppTelovendo.subcategoria'),
        ),
    ]
