# Generated by Django 4.0.4 on 2022-05-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTelovendo', '0010_subcategoria_categoria_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='subcategoria',
            field=models.ManyToManyField(to='AppTelovendo.subcategoria'),
        ),
    ]
